sudo: required

services:
  - docker

before_install:
  - docker build -t mrityunjay1/blog_dev -f Dockerfile.dev .

script:
  - docker run -e CI=true mrityunjay1/blog_dev npm run test


after_success:
  # login to docker

  docker build -t mrityunjay1/blog . 

  echo "$PASS" | docker login -u mrityunjay1 --password-stdin

  docker push mrityunjay1/blog

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "blog"
  env: "Blog-env"
  bucket_name: "elasticbeanstalk-us-east-1-202116681626"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY